# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NumberGenerator <- function(n) {
    .Call(`_RSAPackage_NumberGenerator`, n)
}

gcd <- function(a, b) {
    .Call(`_RSAPackage_gcd`, a, b)
}

pow <- function(a, b) {
    .Call(`_RSAPackage_pow`, a, b)
}

LowLevelPrimeCheck <- function(number) {
    .Call(`_RSAPackage_LowLevelPrimeCheck`, number)
}

compositeCheck <- function(a, d, number, k) {
    .Call(`_RSAPackage_compositeCheck`, a, d, number, k)
}

PrimeCheck <- function(number) {
    .Call(`_RSAPackage_PrimeCheck`, number)
}

generatePrime <- function(n) {
    .Call(`_RSAPackage_generatePrime`, n)
}

messageEncrypt <- function(plaintext, e, n) {
    .Call(`_RSAPackage_messageEncrypt`, plaintext, e, n)
}

messageDecrypt <- function(ciphertext, d, n) {
    .Call(`_RSAPackage_messageDecrypt`, ciphertext, d, n)
}

keyGenerator <- function(p = 2L, q = 7L) {
    .Call(`_RSAPackage_keyGenerator`, p, q)
}

