# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PrimeCheck <- function(number) {
    .Call(`_RSAPackage_PrimeCheck`, number)
}

generatePrime <- function(n) {
    .Call(`_RSAPackage_generatePrime`, n)
}

messageEncrypt <- function(plaintext, e, n) {
    .Call(`_RSAPackage_messageEncrypt`, plaintext, e, n)
}

messageDecrypt <- function(ciphertext, d, n) {
    .Call(`_RSAPackage_messageDecrypt`, ciphertext, d, n)
}

keyGenerator <- function(p, q) {
    .Call(`_RSAPackage_keyGenerator`, p, q)
}

